feat: prevent edit dot files

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -6,7 +6,7 @@ on:
 jobs:
   restrict-to-merge-branch-main:
    runs-on: ubuntu-latest
-   name: Check merge branch
+   name: check-merge-branch
    steps:
      - name: Check merge branch
        if: github.event.pull_request.base.ref == 'main'
@@ -58,3 +58,16 @@ jobs:
         run: pre-commit run --all-files
       - name: success
         run: exit 0
+  check-dot-files:
+    runs-on: ubuntu-latest
+    name: dot-files
+    steps:
+      - name: checkout-repo
+        uses: actions/checkout@v3
+      - name: dot-file-change
+        run: |
+          if git diff --name-only origin/main | grep -i "^\\."; then
+            echo "dot files changed $(git diff --name-only origin/main | grep -i "^\\.") "
+            echo "Error: commiting to dot files are not allowed"
+            exit 1
+          fi
